models/user.py
from extensions import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False, unique=True)
    email = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200))
    created_at = db.Column(db.DateTime(), nullable=False,
                           server_default=db.func.now())
    updated_at = db.Column(db.DateTime(), nullable=False,
                           server_default=db.func.now(), onupdate=db.func.now())

    def __repr__(self):
        return f'<User {self.name}>'

    # property
    def data(self):
        return {
            'id': self.id,
            'username': self.name,
            'email': self.email,
            "password": self.password
        }

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all(cls):
        r = cls.query.all()
        result = []

        for i in r:
            result.append(i.data)
        return result

    @classmethod
    def get_by_id(cls, id):
        return cls.query.filter(cls.id == id).first()

app.py
from flask import Flask
from config import Config
from extensions import db
from flask_migrate import Migrate
from routes import main


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    register_resources(app)
    register_extensions(app)
    return app


def register_extensions(app):
    db.init_app(app)
    migrate = Migrate(app, db)


def register_resources(app):
    app.register_blueprint(main)


if __name__ == '__main__':
    app = create_app()
    app.run('127.0.0.1', 5000)

controllers/user.py
from flask import request
from models.user import User
from extensions import db

def add_user_function():
    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"]
        password = request.form["password"]    
        user = User(
            name = name,
            email = email,
            password = password
        )
        user.save()

        data = {
            'id': user.id,
            'name': user.name,
            'email': user.email,
            'password': user.password
        }
        return data
    
def edit_user_function(data):
    if request.method == "POST":
        data.name = request.form["name"]
        data.email = request.form["email"]
        data.password = request.form["password"]

    db.session.commit()
    return data

routes.py
from flask import Blueprint, render_template
from controllers.user import add_user_function, edit_user_function
from models.user import User
import sys

main = Blueprint('main',__name__) #route name = main

@main.route('/', methods=['GET'])
def home():
        data = User.get_all()
        return render_template('index.html', data = data)

@main.route('/adduser', methods = ['GET','POST'])
def add_user():
        data = add_user_function()
        print(data,file=sys.stderr)
        return render_template('adduser.html', data = data)

@main.route('/edituser/<int:id>', methods = ['GET','POST'])
def edit_user(id):
        user = User.get_by_id(id)
        data = edit_user_function(user)
        
        return render_template('edituser.html', user=user, data=data)

templates/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align_items_center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                           <a href="/">Back to Home</a> 
                        </li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 pd-md--0 mb-md-5 px-md-2 text-center">Add User</h2>
                        <form method="POST", action="/adduser">
                            <div class="form-group">
                                <input type="text" id="name" name="name" class="form-control" placeholder="name"><br/>
                            </div>
                            <div class="form-group">
                                <input type="text" id="email" name="email" class="form-control" placeholder="email"><br/>
                            </div>
                            <div class="form-group">
                                <input type="text" id="password" name="password" class="form-control" placeholder="password"><br/>
                            </div>
                            <br/>
                            <br/>
                            <button type="button" class="btn btn-success text-center">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div> 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/edituser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align_items_center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                           <a href="/">Back to Home</a> 
                        </li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-md-5">
                        <h2 class="mb-4 pb-2 pd-md--0 mb-md-5 px-md-2 text-center">Edit User</h2>
                        <form method="POST", action="/edituser">
                            <div class="form-group">
                                <input type="text" id="name" name="name" class="form-control" placeholder={{user.name}}/><br/>
                            </div>
                            <div class="form-group">
                                <input type="text" id="email" name="email" class="form-control" placeholder={{user.email}}/><br/>
                            </div>
                            <div class="form-group">
                                <input type="text" id="password" name="password" class="form-control" placeholder={{user.password}}/><br/>
                            </div>
                            <br/>
                            <br/>
                            <button type="button" class="btn btn-success text-center">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div> 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="my-5 text-center">
        <button type="button" class="btn btn-primary">
          <a href="{{url_for('main.add_user')}}" class="text-white">Add User</a>
        </button>

        <br/>
        <div class="w-70 d-flex p-5">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% for item in data%}
                        <th scope="row">{{item.id}}</th>
                        <td>{{item.name}}</td>
                        <td>{{item.email}}</td>
                        <td>
                            <button class="btn btn-success">Edit</button>
                            <button class="btn btn-danger">Delete</button>
                        </td>
                    {% endfor%}
                  </tr>
                </tbody>
              </table>
        </div>

    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>